"""esquema inicial

Revision ID: 49b74c185f93
Revises: 
Create Date: 2026-08-16 17:55:30.974626
docker compose exec backend alembic upgrade head
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b74c185f93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caracteristicas_hotel',
    sa.Column('id_caracteristica', sa.Integer(), nullable=False),
    sa.Column('nombre_caracteristica', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_caracteristica'),
    sa.UniqueConstraint('nombre_caracteristica')
    )
    op.create_index(op.f('ix_caracteristicas_hotel_id_caracteristica'), 'caracteristicas_hotel', ['id_caracteristica'], unique=False)
    op.create_table('categoria_servicio',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_categoria_servicio_id_categoria'), 'categoria_servicio', ['id_categoria'], unique=False)
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_table('destinos',
    sa.Column('id_destino', sa.Integer(), nullable=False),
    sa.Column('nombre_destino', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('temporada_alta_inicio', sa.Date(), nullable=True),
    sa.Column('temporada_alta_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_destino')
    )
    op.create_index(op.f('ix_destinos_id_destino'), 'destinos', ['id_destino'], unique=False)
    op.create_table('empleados',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_index(op.f('ix_empleados_id_empleado'), 'empleados', ['id_empleado'], unique=False)
    op.create_table('hoteles',
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('nombre_hotel', sa.String(length=100), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_hotel')
    )
    op.create_index(op.f('ix_hoteles_id_hotel'), 'hoteles', ['id_hotel'], unique=False)
    op.create_table('metodos_pago',
    sa.Column('id_metodo', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_metodo')
    )
    op.create_index(op.f('ix_metodos_pago_id_metodo'), 'metodos_pago', ['id_metodo'], unique=False)
    op.create_table('paquetes',
    sa.Column('id_paquete', sa.Integer(), nullable=False),
    sa.Column('nombre_paquete', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_paquete')
    )
    op.create_index(op.f('ix_paquetes_id_paquete'), 'paquetes', ['id_paquete'], unique=False)
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=100), nullable=False),
    sa.Column('tipo_proveedor', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo_electronico', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('comision_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_index(op.f('ix_proveedores_id_proveedor'), 'proveedores', ['id_proveedor'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('tipo_habitacion',
    sa.Column('id_tipo_habitacion', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('capacidad_personas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_habitacion')
    )
    op.create_index(op.f('ix_tipo_habitacion_id_tipo_habitacion'), 'tipo_habitacion', ['id_tipo_habitacion'], unique=False)
    op.create_table('habitaciones',
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('id_tipo_habitacion', sa.Integer(), nullable=False),
    sa.Column('numero_habitacion', sa.String(length=20), nullable=False),
    sa.Column('precio_noche', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_hotel'], ['hoteles.id_hotel'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_habitacion'], ['tipo_habitacion.id_tipo_habitacion'], ),
    sa.PrimaryKeyConstraint('id_habitacion'),
    sa.UniqueConstraint('id_hotel', 'numero_habitacion', name='uq_hotel_numero')
    )
    op.create_index(op.f('ix_habitaciones_id_habitacion'), 'habitaciones', ['id_habitacion'], unique=False)
    op.create_table('hotel_caracteristicas',
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('id_caracteristica', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_caracteristica'], ['caracteristicas_hotel.id_caracteristica'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_hotel'], ['hoteles.id_hotel'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_hotel', 'id_caracteristica')
    )
    op.create_table('paquete_hotel',
    sa.Column('id_paquete', sa.Integer(), nullable=False),
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('noches_incluidas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_hotel'], ['hoteles.id_hotel'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paquete'], ['paquetes.id_paquete'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_paquete', 'id_hotel')
    )
    op.create_table('preferencias_cliente',
    sa.Column('id_preferencia', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('intereses', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('compania', sa.String(length=20), nullable=True),
    sa.Column('presupuesto', sa.String(length=20), nullable=True),
    sa.Column('clima', sa.String(length=20), nullable=True),
    sa.Column('ritmo', sa.String(length=20), nullable=True),
    sa.Column('transporte', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_preferencia'),
    sa.UniqueConstraint('id_cliente')
    )
    op.create_index(op.f('ix_preferencias_cliente_id_preferencia'), 'preferencias_cliente', ['id_preferencia'], unique=False)
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('id_paquete', sa.Integer(), nullable=True),
    sa.Column('fecha_reserva', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('numero_personas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('canal_origen', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_paquete'], ['paquetes.id_paquete'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index(op.f('ix_reservas_id_reserva'), 'reservas', ['id_reserva'], unique=False)
    op.create_table('servicios',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_destino', sa.Integer(), nullable=True),
    sa.Column('duracion_horas', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_servicio.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_destino'], ['destinos.id_destino'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_index(op.f('ix_servicios_id_servicio'), 'servicios', ['id_servicio'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo_electronico'),
    sa.UniqueConstraint('id_cliente'),
    sa.UniqueConstraint('id_empleado'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('historial_reservas',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('fecha_cambio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_empleado_responsable', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado_responsable'], ['empleados.id_empleado'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_reservas_id_historial'), 'historial_reservas', ['id_historial'], unique=False)
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id_metodo'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pagos_id_pago'), 'pagos', ['id_pago'], unique=False)
    op.create_table('paquete_servicios',
    sa.Column('id_paquete', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('dia_actividad', sa.Integer(), nullable=True),
    sa.Column('incluido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_paquete'], ['paquetes.id_paquete'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_paquete', 'id_servicio')
    )
    op.create_table('recuperacion_password',
    sa.Column('id_recuperacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('token_recuperacion', sa.Text(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_expiracion', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_recuperacion')
    )
    op.create_index(op.f('ix_recuperacion_password_id_recuperacion'), 'recuperacion_password', ['id_recuperacion'], unique=False)
    op.create_table('reserva_habitaciones',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('fecha_checkin', sa.Date(), nullable=True),
    sa.Column('fecha_checkout', sa.Date(), nullable=True),
    sa.Column('precio_acordado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitaciones.id_habitacion'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva', 'id_habitacion')
    )
    op.create_table('reserva_servicios',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('fecha_servicio', sa.Date(), nullable=True),
    sa.Column('numero_personas', sa.Integer(), nullable=True),
    sa.Column('precio_acordado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], ),
    sa.PrimaryKeyConstraint('id_reserva', 'id_servicio')
    )
    op.create_table('servicio_proveedor',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('precio_proveedor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('es_proveedor_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_servicio', 'id_proveedor')
    )
    op.create_table('sesiones_usuario',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('direccion_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_expiracion', sa.TIMESTAMP(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index(op.f('ix_sesiones_usuario_id_sesion'), 'sesiones_usuario', ['id_sesion'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_sesiones_usuario_id_sesion'), table_name='sesiones_usuario')
    op.drop_table('sesiones_usuario')
    op.drop_table('servicio_proveedor')
    op.drop_table('reserva_servicios')
    op.drop_table('reserva_habitaciones')
    op.drop_index(op.f('ix_recuperacion_password_id_recuperacion'), table_name='recuperacion_password')
    op.drop_table('recuperacion_password')
    op.drop_table('paquete_servicios')
    op.drop_index(op.f('ix_pagos_id_pago'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_historial_reservas_id_historial'), table_name='historial_reservas')
    op.drop_table('historial_reservas')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_servicios_id_servicio'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_reservas_id_reserva'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_preferencias_cliente_id_preferencia'), table_name='preferencias_cliente')
    op.drop_table('preferencias_cliente')
    op.drop_table('paquete_hotel')
    op.drop_table('hotel_caracteristicas')
    op.drop_index(op.f('ix_habitaciones_id_habitacion'), table_name='habitaciones')
    op.drop_table('habitaciones')
    op.drop_index(op.f('ix_tipo_habitacion_id_tipo_habitacion'), table_name='tipo_habitacion')
    op.drop_table('tipo_habitacion')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_proveedores_id_proveedor'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_paquetes_id_paquete'), table_name='paquetes')
    op.drop_table('paquetes')
    op.drop_index(op.f('ix_metodos_pago_id_metodo'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    op.drop_index(op.f('ix_hoteles_id_hotel'), table_name='hoteles')
    op.drop_table('hoteles')
    op.drop_index(op.f('ix_empleados_id_empleado'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_destinos_id_destino'), table_name='destinos')
    op.drop_table('destinos')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_categoria_servicio_id_categoria'), table_name='categoria_servicio')
    op.drop_table('categoria_servicio')
    op.drop_index(op.f('ix_caracteristicas_hotel_id_caracteristica'), table_name='caracteristicas_hotel')
    op.drop_table('caracteristicas_hotel')
    # ### end Alembic commands ###
