"""crear tabla resenas

Revision ID: 83731da37b5e
Revises: 523e6283e58b
Create Date: 2026-08-22 02:03:42.375677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83731da37b5e'
down_revision: Union[str, None] = '523e6283e58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'resenas',
        sa.Column('id_resena', sa.Integer(), nullable=False),
        sa.Column('id_reserva', sa.Integer(), nullable=False),
        sa.Column('id_cliente', sa.Integer(), nullable=False),
        sa.Column('id_hotel', sa.Integer(), nullable=False),
        sa.Column('calificacion', sa.Integer(), nullable=False),
        sa.Column('comentario', sa.Text(), nullable=False),
        sa.Column('foto_url', sa.String(length=500), nullable=True),
        sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.CheckConstraint('calificacion BETWEEN 1 AND 5', name='ck_resenas_calificacion'),
        sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['id_hotel'], ['hoteles.id_hotel'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id_resena'),
        sa.UniqueConstraint('id_reserva', name='uq_resenas_id_reserva'),
    )
    op.create_index(op.f('ix_resenas_id_resena'), 'resenas', ['id_resena'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resenas_id_resena'), table_name='resenas')
    op.drop_table('resenas')
    # ### end Alembic commands ###